package ProfilePackage;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Home extends javax.swing.JFrame {

    public Home() {
        this.getContentPane().setBackground(Color.decode("#DCE7F7"));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 5, dim.height / 5);
        initComponents();

        LogoutLbl.setForeground(Color.decode("#FAA8C0"));
        RegisterLbl.setForeground(Color.decode("#FBB348"));

        items.setBackground(Color.decode("#92ACEF"));
        items.setForeground(Color.white);
        items.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        items = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LogoutLbl = new javax.swing.JLabel();
        RegisterLbl = new javax.swing.JLabel();
        items1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(777, 500));
        getContentPane().setLayout(null);

        items.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        items.setText("Products");
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemsMouseExited(evt);
            }
        });
        items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsActionPerformed(evt);
            }
        });
        getContentPane().add(items);
        items.setBounds(390, 350, 270, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProfilePackage/bloom-37 1.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 80, 350, 240);

        jPanel1.setBackground(new java.awt.Color(27, 173, 222));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rudaw", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("پڕۆژەی دەرمانخانەی کەوسەر");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 20, 460, 100);

        LogoutLbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LogoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LogoutLbl.setText("Logout");
        LogoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutLblMouseExited(evt);
            }
        });
        jPanel1.add(LogoutLbl);
        LogoutLbl.setBounds(704, 30, 60, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, -10, 890, 240);

        RegisterLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterLbl.setText("Create New Account");
        RegisterLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterLblMouseExited(evt);
            }
        });
        getContentPane().add(RegisterLbl);
        RegisterLbl.setBounds(300, 400, 170, 15);

        items1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        items1.setText("Selling");
        items1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                items1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                items1MouseExited(evt);
            }
        });
        items1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                items1ActionPerformed(evt);
            }
        });
        getContentPane().add(items1);
        items1.setBounds(110, 350, 270, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsActionPerformed
        new Items().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemsActionPerformed

    private void LogoutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseClicked
        int p = JOptionPane.showConfirmDialog(this, "Do you want to Logout?", "Logging out", JOptionPane.YES_NO_OPTION);

        if (p == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutLblMouseClicked

    private void LogoutLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseEntered
        LogoutLbl.setForeground(Color.decode("#916483"));
    }//GEN-LAST:event_LogoutLblMouseEntered

    private void LogoutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutLblMouseExited
        LogoutLbl.setForeground(Color.decode("#FAA8C0"));
    }//GEN-LAST:event_LogoutLblMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        new Items().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void RegisterLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLblMouseClicked
        new Register().show();
        this.dispose();
    }//GEN-LAST:event_RegisterLblMouseClicked

    private void RegisterLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLblMouseEntered

        RegisterLbl.setForeground(Color.decode("#9CAC82"));
    }//GEN-LAST:event_RegisterLblMouseEntered

    private void RegisterLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterLblMouseExited
        RegisterLbl.setForeground(Color.decode("#F2AB44"));
    }//GEN-LAST:event_RegisterLblMouseExited

    private void itemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseEntered
        items.setBackground(Color.decode("#76CEEB"));
    }//GEN-LAST:event_itemsMouseEntered

    private void itemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseExited
        items.setBackground(Color.decode("#92ACEF"));
    }//GEN-LAST:event_itemsMouseExited

    private void items1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_items1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_items1MouseEntered

    private void items1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_items1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_items1MouseExited

    private void items1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_items1ActionPerformed
        Selling selling = new Selling();
        selling.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_items1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutLbl;
    private javax.swing.JLabel RegisterLbl;
    private javax.swing.JButton items;
    private javax.swing.JButton items1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
